###################  数据库配置  ###################
spring:
  datasource:
    #数据库驱动
    driver-class-name: com.mysql.jdbc.Driver
    #数据库链接地址
    url: jdbc:mysql://127.0.0.1:3306/code-demo?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false
    #数据库用户名
    username: root
    #数据库密码
    password: 123456
    #如果不使用默认的数据源 （com.zaxxer.hikari.HikariDataSource）
    type: com.alibaba.druid.pool.DruidDataSource

###################  自定义  ###################
name: www
info: "name=${name}"