###################  项目启动端口  ###################
server:
  #项目启动的端口号
  port: 8888
  servlet:
    #项目访问的url路径根路径，例如/xxx
    context-path: /

###################  数据库配置  ###################
mybatis:
  #指定生成的*.xml文件路径
  mapper-locations: classpath*:com/wander/**/dao/*.xml

###################  默认环境  ###################
spring:
  profiles:
    active: dev
