###################  项目启动端口  ###################
server:
  #项目启动的端口号
  port: 8888
  servlet:
    #项目访问的url路径根路径，例如/xxx
    context-path: /

###################  数据库配置  ###################
mybatis:
  #指定生成的*.xml文件路径
  mapper-locations: classpath*:com/wander/**/dao/*.xml
  configuration:
    #驼峰命名转换
    map-underscore-to-camel-case: true
    #控制台打印sql语句
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

###################  默认环境  ###################
spring:
  profiles:
    active: dev
