###################  项目启动端口  ###################
server:
  #项目启动的端口号
  port: 8888
  servlet:
    #项目访问的url路径根路径，例如/xxx
    context-path: /

###################  数据库配置  ###################
spring:
  datasource:
    #数据库驱动
    driver-class-name: com.mysql.jdbc.Driver
    #数据库链接地址
    url: jdbc:mysql://127.0.0.1:3306/code-demo?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false
    #数据库用户名
    username: root
    #数据库密码
    password: 123456
  profiles:
    active: test
mybatis:
  #指定生成的*.xml文件路径
  mapper-locations: classpath*:com/wander/**/dao/*.xml

